title: <p align="center"> Aryan Baruah </p>
logo: /assets/img/AB.jpeg

description:
  <p align="center">
  
  <br>   
  I am a MEAN stack developer leading AIML.
  <br>
  </p>



theme: jekyll-theme-minimal
